package com.avi.journal.data

import android.app.Activity
import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import com.google.android.gms.tasks.Task
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlinx.coroutines.suspendCancellableCoroutine

/** Who is signed in. Deliberately small — the app needs a name, not a profile. */
data class AppUser(
    val uid: String,
    val displayName: String?,
    val email: String?,
)

/**
 * Google sign-in through Credential Manager, exchanged for a Firebase session.
 * Same approach as WeightTracker, including the reason for the odd lookup below.
 *
 * The web client ID is looked up by resource NAME rather than referenced as
 * R.string.default_web_client_id: that constant is generated by the
 * google-services plugin from google-services.json, so referencing it directly
 * would make the whole app fail to compile on a checkout that hasn't been wired
 * to a Firebase project yet. This way an unconfigured build still runs, and the
 * sign-in screen explains what's missing instead of the build breaking.
 */
class AccountManager(private val context: Context) {

    private val auth: FirebaseAuth? get() = runCatching { FirebaseAuth.getInstance() }.getOrNull()

    val currentUser: AppUser?
        get() = auth?.currentUser?.let {
            AppUser(uid = it.uid, displayName = it.displayName, email = it.email)
        }

    val isConfigured: Boolean get() = webClientId() != null

    suspend fun signIn(activity: Activity): Result<AppUser> {
        val clientId = webClientId()
            ?: return Result.failure(
                IllegalStateException(
                    "This build isn't connected to a Firebase project yet — " +
                        "google-services.json is missing."
                )
            )

        return runCatching {
            val option = GetGoogleIdOption.Builder()
                // false, so someone signing in for the first time still sees
                // their accounts rather than an empty sheet.
                .setFilterByAuthorizedAccounts(false)
                .setServerClientId(clientId)
                .build()

            val request = GetCredentialRequest.Builder()
                .addCredentialOption(option)
                .build()

            val response = CredentialManager.create(context).getCredential(activity, request)
            val credential = response.credential

            if (credential !is CustomCredential ||
                credential.type != GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
            ) {
                throw IllegalStateException("That wasn't a Google account.")
            }

            val idToken = GoogleIdTokenCredential.createFrom(credential.data).idToken
            val firebase = auth ?: throw IllegalStateException("Firebase isn't available.")
            val result = firebase
                .signInWithCredential(GoogleAuthProvider.getCredential(idToken, null))
                .await()

            val user = result.user ?: throw IllegalStateException("Signed in, but got no account back.")
            AppUser(uid = user.uid, displayName = user.displayName, email = user.email)
        }
    }

    fun signOut() {
        auth?.signOut()
    }

    private fun webClientId(): String? {
        val id = context.resources.getIdentifier(
            "default_web_client_id",
            "string",
            context.packageName,
        )
        return if (id == 0) null else context.getString(id)
    }
}

/**
 * Bridges Play services' Task to a coroutine. Hand-rolled rather than pulling in
 * kotlinx-coroutines-play-services: it is eight lines, and one fewer dependency
 * is one fewer version to keep in step.
 */
internal suspend fun <T> Task<T>.await(): T = suspendCancellableCoroutine { continuation ->
    addOnSuccessListener { value -> continuation.resume(value) }
    addOnFailureListener { error -> continuation.resumeWithException(error) }
    addOnCanceledListener { continuation.cancel() }
}
